# Generated by Django 4.2.1 on 2023-05-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_pantry'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantry',
            name='has_it',
            field=models.BooleanField(null=True),
        ),
    ]
