# Generated by Django 4.2.1 on 2023-05-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_remove_pantry_has_it'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pantry',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
