# Generated by Django 4.2.1 on 2023-06-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_alter_recipe_chat_ingredients_alter_recipe_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_saved',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user_ingredients',
            field=models.ManyToManyField(to='recipe.ingredient'),
        ),
    ]
