# Generated by Django 4.2.1 on 2023-06-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_recipe_is_saved_alter_recipe_user_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_saved',
            field=models.BooleanField(default=0),
        ),
    ]
