# Generated by Django 4.2.1 on 2023-06-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_recipe_created_at_recipe_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='serves',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
